name: Action for bump ver
description: Action for bump ver

inputs:
  githubToken:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        token: ${{ inputs.githubToken }}
        ref: ${{ inputs.ref || github.ref }}
        persist-credentials: false
        fetch-depth: 0
    - uses: KimAlexander/release-it/projects/setup-git@main
      with:
        token: ${{ inputs.githubToken }}
    - shell: bash
      name: Create bump_ver branch from develop
      run: git checkout -b bump_ver origin/develop
