name: Version bump

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: false
        default: minor
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: KimAlexander/action-bump/actions/release-it@develop
        with:
          mode: ${{ github.event.inputs.mode || 'minor' }}
          githubToken: ${{ secrets.PAT_FOR_BOT }}
      - uses: KimAlexander/action-bump/actions/read-package-json@develop
        id: info
      - uses: KimAlexander/action-bump/actions/create-pr@develop
        with:
          githubToken: ${{ secrets.PAT_FOR_BOT }}
          base: ${{ steps.info.outputs.base }}
          head: feature/bump_ver
          title: "Bump version to ${{ steps.info.outputs.version }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true